app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
	login,
	logout,
	password_reset,
	password_reset_done,
	password_reset_confirm,
	password_reset_complete,
	)

from . import views

app_name = 'app'
urlpatterns = [
	url(r'^$', views.Home, name='home'),
	url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
	url(r'^profile/$', views.Profile , name='profile'),
	url(r'^profile/edit/$', views.Edit_profile , name='edit_profile'),
	url(r'^profile/editpic/$', views.Edit_profilepic , name='edit_profilepic'),
	url(r'^register/$', views.Register , name='register'),
	url(r'^change-password/$', views.Change_Password , name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html',
											   'post_reset_redirect': 'app:password_reset_done',
											   'email_template_name': 'accounts/reset_password_email.html'},
												name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
														  name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
												password_reset_confirm,
												{'template_name': 'accounts/reset_password_confirm.html',
												 'post_reset_redirect': 'app:password_reset_complete'},
												  name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'},
																 name='password_reset_complete'),
	url(r'^inbox/$', views.Inbox , name='inbox'),
	url(r'^msg/(?P<pk>\d+)/$', views.Msg_View , name='msg'),
	url(r'^new_msg/$', views.New_Msg , name='new_msg'),
	url(r'^del_msg/$', views.Del_Msg , name='del_msg'),
	url(r'^read_msg/$', views.Read_Msg , name='read_msg'),
	url(r'^unread_msg/$', views.Unread_Msg , name='unread_msg'),
	url(r'^side_menu/$', views.Side_Menu , name='side_menu'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
	url(r'^app/', include('app.urls')),
	url(r'^financ/', include('financ.urls')),
	url(r'^ponto/', include('ponto.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

ponto/urls.py
from django.conf.urls import url
from . import views

app_name = 'ponto'
urlpatterns = [    
	url(r'^$', views.Ponto_List, name="ponto_list"),
	url(r'^add/$', views.Ponto_Add, name="ponto_add"),
	url(r'^view/(?P<pk>\d+)/$', views.Ponto_View, name='ponto_view'),
	url(r'^edit/(?P<pk>\d+)/$', views.Ponto_Edit, name='ponto_edit'),
	url(r'^del/$', views.Ponto_Del, name='ponto_del'),
	url(r'^paramponto/$', views.ParamPonto_Edit, name='paramponto_edit'),
]

ponto/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
import os

# Create your models here.

class PontoUser(models.Manager):
	def get_queryset(self):
		qs = super(PontoUser, self).get_queryset()		
		return qs.filter(observacao='teste')

class Ponto(models.Model):
	usuario      = models.ForeignKey(User, on_delete=models.CASCADE,default='')
	dia          = models.DateField()
	hora         = models.TimeField()			
	observacao   = models.CharField(max_length=40, blank=True)		
	tipo         = models.CharField(max_length=9,
									choices=(('entrada','Entrada'),('saida','Saida')),
									default="entrada")
	comprovante  = models.FileField(upload_to='ponto/comprovantes/', blank=True, null=True)

	def __str__(self):
		retorno = str(self.dia) + '  ' + str(self.hora)
		return retorno

	objects = models.Manager()
	objects_user = PontoUser()

	class Meta:
		permissions = (('acesso_app_ponto', 'Pode acessar Ponto'),
					   ('adicionar_anexo','Pode anexar foto'),)

class ParamPonto(models.Model):
	usuario      = models.ForeignKey(User, on_delete=models.CASCADE,default='')
	entrada      = models.TimeField()
	saida        = models.TimeField()
	tolerancia   = models.TimeField()


@receiver(models.signals.post_delete, sender=Ponto)
def delete_file_on_del_pagto(sender, instance, **kwargs):    
	if instance.comprovante:
		if os.path.isfile(instance.comprovante.path):
			os.remove(instance.comprovante.path)

@receiver(models.signals.pre_save, sender=Ponto)
def delete_file_on_change_pagto(sender, instance, **kwargs):    
	if not instance.pk:
		return False

	try:
		old_file = Ponto.objects.get(pk=instance.pk).comprovante
	except Ponto.DoesNotExist:
		return False

	new_file = instance.comprovante
	if not old_file == new_file:
		if old_file:
			if os.path.isfile(old_file.path):
				os.remove(old_file.path)

ponto/forms.py
from django import forms
from django.forms.widgets import TextInput
from .models import Ponto, ParamPonto

class PontoForm(forms.ModelForm):    
	class Meta:
		model = Ponto
		fields = ('dia',
				  'hora',       
				  'observacao', 	
				  'tipo',
				  'comprovante'
				)
		widgets = {
			'dia': TextInput(attrs={'type': 'date'}),
			'hora': TextInput(attrs={'type': 'time'}),
		}

class PontoFormView(forms.ModelForm):        
	class Meta:
		model = Ponto
		fields = ('dia',
				  'hora',
				  'observacao',
				  'tipo',
				)
		widgets = {
			'dia': TextInput(attrs={'type': 'date', 'disabled': True}),
			'hora': TextInput(attrs={'type': 'time', 'disabled': True}),
			'observacao': TextInput(attrs={'disabled': True}),
			'tipo': TextInput(attrs={'disabled': True}),
		}

class ParamPontoForm(forms.ModelForm):    
	class Meta:
		model = ParamPonto
		fields = ('entrada',
				  'saida',
				  'tolerancia'

				)
		widgets = {
			'entrada': TextInput(attrs={'type': 'time'}),
			'saida': TextInput(attrs={'type': 'time'}),
			'tolerancia': TextInput(attrs={'type': 'time'}),
		}

ponto/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import permission_required
from .forms import(
	PontoForm,
	PontoFormView,
	ParamPontoForm,
	)
from .models import(
	Ponto,
	ParamPonto,
	)
from django.contrib import messages
from datetime import datetime, timedelta
#import pdb; pdb.set_trace()

@permission_required('ponto.acesso_app_ponto', raise_exception=True)
def Ponto_List(request):
	dia = datetime.today() - timedelta(days=10)
	p_dt_ini    = request.GET.get('dt_ini', dia.strftime('%Y-%m-%d'))
	p_dt_fim    = request.GET.get('dt_fim', datetime.today().strftime('%Y-%m-%d'))
	p_rs_ponto  = request.GET.get('rs_ponto', 'all')

	periodo = {'dt_ini': p_dt_ini,
			   'dt_fim': p_dt_fim}

	try:
		ponto = Ponto.objects.filter(usuario=request.user,
									 dia__range=(p_dt_ini, p_dt_fim))	
	except:
		messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               
		return redirect('ponto:ponto_list')
	ponto = ponto.order_by('dia','hora')
	
	try:
		paramponto = ParamPonto.objects.get(usuario=request.user)
	except ParamPonto.DoesNotExist:
		paramponto = None
	if not paramponto:
		paramponto = ParamPonto.objects.create(usuario=request.user,
								  entrada="07:30",
								  saida="17:18",
								  tolerancia="00:00")

	parampontoform = ParamPontoForm(instance=paramponto)	

	for i in ponto:	
		i.exc = False	
		if i.tipo == 'entrada':			
			v_entrad   = timedelta(hours=paramponto.entrada.hour,minutes=paramponto.entrada.minute) + timedelta(hours=paramponto.tolerancia.hour,minutes=paramponto.tolerancia.minute)
			v_entrad_l = timedelta(hours=paramponto.entrada.hour,minutes=paramponto.entrada.minute) - timedelta(hours=paramponto.tolerancia.hour,minutes=paramponto.tolerancia.minute)
			if v_entrad < timedelta(hours=i.hora.hour,minutes=i.hora.minute):
				i.banco = timedelta(hours=i.hora.hour,minutes=i.hora.minute) - timedelta(hours=paramponto.entrada.hour,minutes=paramponto.entrada.minute)
				i.cor = "red"
				i.exc = True		
			elif v_entrad_l > timedelta(hours=i.hora.hour,minutes=i.hora.minute):
				i.banco = timedelta(hours=paramponto.entrada.hour,minutes=paramponto.entrada.minute) - timedelta(hours=i.hora.hour,minutes=i.hora.minute)
				i.cor = "green"		
				i.exc = True		
		else:
			v_saida   = timedelta(hours=paramponto.saida.hour,minutes=paramponto.saida.minute) + timedelta(hours=paramponto.tolerancia.hour,minutes=paramponto.tolerancia.minute)
			v_saida_l = timedelta(hours=paramponto.saida.hour,minutes=paramponto.saida.minute) - timedelta(hours=paramponto.tolerancia.hour,minutes=paramponto.tolerancia.minute)
			if v_saida < timedelta(hours=i.hora.hour,minutes=i.hora.minute):
				i.banco = timedelta(hours=i.hora.hour,minutes=i.hora.minute) - timedelta(hours=paramponto.saida.hour,minutes=paramponto.saida.minute)
				i.cor = "green"		
				i.exc = True		
			elif v_saida_l > timedelta(hours=i.hora.hour,minutes=i.hora.minute):
				i.banco = timedelta(hours=paramponto.saida.hour,minutes=paramponto.saida.minute) - timedelta(hours=i.hora.hour,minutes=i.hora.minute) 
				i.cor = "red"		
				i.exc = True

	args = {'ponto': ponto,
			'periodo':periodo,
			'paramponto': parampontoform,
			'parampontoform': paramponto,
			'p_rs_ponto': p_rs_ponto}

	return render(request, 'ponto/ponto.html', args)

@permission_required('ponto.acesso_app_ponto', raise_exception=True)
def Ponto_Add(request):
	if request.method == 'POST':
		form = PontoForm(request.POST, request.FILES)
		if form.is_valid():
			ponto = form.save(commit=False)
			ponto.usuario = request.user
			ponto.save()
			messages.success(request, "Informações atualizadas com sucesso.", extra_tags='alert-success alert-dismissible')			
			return redirect('ponto:ponto_list')
		else:
			messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               
	else:
		data = {'dia': datetime.today().strftime('%Y-%m-%d'),
				'hora': datetime.today().strftime('%H:%M')}
		form = PontoForm(initial=data)

	args = {'form': form}

	return render(request, 'ponto/ponto_add.html', args)

@permission_required('ponto.acesso_app_ponto', raise_exception=True)
def Ponto_View(request,pk):	
	ponto = get_object_or_404(Ponto, pk=pk)
	if ponto.usuario != request.user:
		messages.error(request, "Acesso negado!", extra_tags='alert-error alert-dismissible')			
		return redirect('ponto:ponto_list')

	form = PontoFormView(instance=ponto)    

	args = {'ponto': ponto, 'form': form}

	return render(request, 'ponto/ponto_view.html', args)

@permission_required('ponto.acesso_app_ponto', raise_exception=True)
def Ponto_Edit(request,pk):
	ponto = get_object_or_404(Ponto, pk=pk)
	if ponto.usuario != request.user:
		messages.error(request, "Acesso negado!", extra_tags='alert-error alert-dismissible')			
		return redirect('ponto:ponto_list')
	if request.method == 'POST':
		form = PontoForm(request.POST, request.FILES, instance=ponto)        
		if form.is_valid():
			form.save()
			messages.success(request, "Informações atualizadas com sucesso.", extra_tags='alert-success alert-dismissible')
			return redirect('ponto:ponto_list')
		else:
			messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')
	else:						
		form = PontoForm(instance=ponto)
	args = {'form': form, 'ponto': ponto}

	return render(request, 'ponto/ponto_edit.html', args)

@permission_required('ponto.acesso_app_ponto', raise_exception=True)
def Ponto_Del(request):
	if request.POST and request.is_ajax():
		if request.POST.getlist('ponto_lista[]'):
			ponto_list = request.POST.getlist('ponto_lista[]')
			for i in ponto_list:
				ponto = Ponto.objects.get(pk=i)
				if ponto.usuario != request.user:
					messages.error(request, "Acesso negado!", extra_tags='alert-error alert-dismissible')
					return redirect('ponto:ponto_list')
				ponto.delete()
			messages.success(request, "Ponto excluido com sucesso.", extra_tags='alert-success alert-dismissible')
		else:
			messages.error(request, "Nenhum ponto selecionado.", extra_tags='alert-error alert-dismissible')

	return HttpResponse('')

@permission_required('ponto.acesso_app_ponto', raise_exception=True)
def ParamPonto_Edit(request):
	if request.is_ajax():
		if request.method == 'POST':
			paramponto = ParamPonto.objects.get(usuario=request.user)
			form = ParamPontoForm(request.POST, instance=paramponto)
			if form.is_valid():				
				form.save()				
			
			return HttpResponse('')   

ponto/templates/ponto/ponto.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ponto
        <small>Lista</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            <a class="btn btn-default" href="{% url 'ponto:ponto_add' %}"><span class="fa fa-plus-circle"></span></a>
            <a class="btn btn-default" href="" data-toggle="modal" data-target="#div-btn-param"><span class="fa fa-clock-o"></span></a> 
            
            <div class="modal fade" tabindex="-1" role="dialog" id="div-btn-param">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">Paramêtros Ponto:</h4>
                        </div>
                        <div class="modal-body">                            
                            <form method="POST" id="form_paramponto">
                                <table class="table" style="max-width:300px;">  {% csrf_token %}
                                    {{ paramponto.as_table }}                                        
                                </table>                                
                                <a class="btn btn-default btn-del-ok" id="salva_paramponto"><span class="fa fa-check"></span></a>                        
                                <a class="btn btn-default btn-del-cancel" data-dismiss="modal" aria-label="Close"><span class="fa fa-times"></span></a>
                            </form>
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>
            <p></p>
            <form method="GET">                
                <input name="dt_ini" class="input-sm" type="date" value="{{ periodo.dt_ini }}">
                <i class="fa fa-chevron-left"></i>
                <i class="fa fa-chevron-right"></i>                
                <input name="dt_fim" class="input-sm" type="date" value="{{ periodo.dt_fim }}">
                <button class="btn btn-default btn-sm" type="submit" id="btn_filtro"><span class="glyphicon glyphicon-search"></span></button>
                <br>
                <input type="radio" class="rs_ponto" id="rs_ponto_all" name="rs_ponto" value="all"> Todos Registros 
                <input type="radio" class="rs_ponto" id="rs_ponto_exc" name="rs_ponto" value="exc"> Apenas Excedentes                
            </form>
            <p></p>            
            <div class="table-responsive">
                <div style="max-width:600px;">
                    <table class="table table-bordered table-selectable" id="table_despesa">
                        <thead>
                            <th style="max-width:10px;">Tipo</th>
                            <th>Dia</th>
                            <th>Hora</th>
                            <th>Observ.</th>
                            <th>Banco</th>
                        </thead>
                        <tbody>
                            {% for i in ponto %}    
                            {% if i.exc == False and p_rs_ponto == 'exc' %}                                                                
                            {% else %}
                            <tr id="{{ i.pk }}" style="color:{{ i.cor }}">
                                <td class="colunatable">{{ i.tipo }}</td>                                                                                
                                <td class="colunatable">{{ i.dia|date:"d/m/Y" }}</td>
                                <td class="colunatable">{{ i.hora }}</td>                                                                                
                                <td class="colunatable">{{ i.observacao }}</td>
                                <td class="colunatable">{{ i.banco }}</td>
                            </tr>
                            {% endif %}                                    
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>            
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

{% load static %}
<script type="text/javascript" src="{% static 'app/plugins/datatables/jquery.dataTables.min.js'  %}"></script>
<script type="text/javascript" src="{% static 'app/plugins/datatables/dataTables.bootstrap.min.js'  %}"></script>

<script type="text/javascript">    
    $.urlParam = function(name){
        var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);        
        if (results != null){
            return results[1];            
        };        
    }
    $(document).ready(function(){                
        $('#table_despesa').DataTable({
          "paging": false,
          "lengthChange": false,
          "searching": true,
          "ordering": false,
          "info": false,
          "autoWidth": true,  
          "dom": '<"top"i>rt<"bottom"flp><"clear">'
        });
        v_rs_ponto = $.urlParam('rs_ponto');
        if (v_rs_ponto == 'exc'){
            $("#rs_ponto_exc").prop("checked", true);
        }
        else{
            $("#rs_ponto_all").prop("checked", true);
        };
        
    });
    $(".rs_ponto").change(function(e) {        
        $("#btn_filtro").click();
    });
    $(".colunatable").click(function(e) {
        chave = $(this).closest("tr").attr("id")
        window.location.href = "view/" + chave;
    });        
    
    $("#salva_paramponto").click(function(e){ 
        $.ajax({
            url:"{% url 'ponto:paramponto_edit' %}",
            type: "POST",            
            data: $("#form_paramponto").serialize(),            
            success:function(response){ 
                location.reload();                                   
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){
                
            }
        });
    });
    
</script>
{% endblock javascript %}

ponto/templates/ponto/ponto_add.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ponto
        <small>Adiciona</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            <form method="POST" enctype="multipart/form-data">
                <table class="table" style="max-width:300px;">  {% csrf_token %}
                    {{ form.as_table }}                    
                </table>
                <button class="btn btn-default" type="submit">Salvar</button>
                <a class="btn btn-default" href="{% url 'ponto:ponto_list' %}">Cancelar</a>
            </form>
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    

</script>
{% endblock javascript %}

ponto/templates/ponto/ponto_edit.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ponto
        <small>Edita</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            <form method="POST" enctype="multipart/form-data">
                <table class="table" style="max-width:300px;">  {% csrf_token %}
                    {{ form.as_table }}                    
                </table>
                <button class="btn btn-default" type="submit">Salvar</button>
                <a class="btn btn-default" href="{% url 'ponto:ponto_view' pk=ponto.pk %}">Voltar</a>
            </form>
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    

</script>
{% endblock javascript %}

ponto/templates/ponto/ponto_view.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Ponto
        <small>Detalhe</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            
            <table class="table" style="max-width:300px;">  {% csrf_token %}
                {{ form.as_table }}             
                <tr><th>Comprovante:      </th><td> {% if ponto.comprovante %}<a href="{{ ponto.comprovante.url }}">{{ ponto.comprovante }} </a> {% endif %} </td></tr>
            </table>
            <p></p>
            <a class="btn btn-default" href="{% url 'ponto:ponto_edit' pk=ponto.pk %}">Editar</a> 
            <a class="btn btn-default" href="" data-toggle="modal" data-target="#div-btn-mes">Deletar</a> 
            <a class="btn btn-default" href="{% url 'ponto:ponto_list' %}">Cancelar</a>

            <div class="modal fade" tabindex="-1" role="dialog" id="div-btn-mes">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">Dia: {{ form.dia.value|date:"d/m/Y" }} Hora: {{ form.hora.value }}</h4>
                        </div>
                        <div class="modal-body">
                            Tem certeza que deseja deletar o ponto selecionado ?
                            <p></p>
                            <a class="btn btn-default btn-del-ok" id="bt-confirm-del"><span class="fa fa-check"></span></a>                        
                            <a class="btn btn-default btn-del-cancel" data-dismiss="modal" aria-label="Close"><span class="fa fa-times"></span></a>

                        </div>
                    </div>
                </div>
            </div>
        
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    $('#bt-confirm-del').click(function(e) {
        var ponto_list = [];        
        ponto_list.push({{ ponto.pk }});
        $.ajax({
            url:"{% url 'ponto:ponto_del' %}",
            type: "POST",            
            data: {ponto_lista: ponto_list, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success:function(response){
            window.location.href= "{% url 'ponto:ponto_list' %}"
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });        
    }); 

</script>
{% endblock javascript %}