app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
	login,
	logout,
	password_reset,
	password_reset_done,
	password_reset_confirm,
	password_reset_complete,
	)

from . import views

app_name = 'app'
urlpatterns = [
	url(r'^$', views.Home, name='home'),
	url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
	url(r'^profile/$', views.Profile , name='profile'),
	url(r'^profile/edit/$', views.Edit_profile , name='edit_profile'),
	url(r'^profile/editpic/$', views.Edit_profilepic , name='edit_profilepic'),
	url(r'^register/$', views.Register , name='register'),
	url(r'^change-password/$', views.Change_Password , name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html',
											   'post_reset_redirect': 'app:password_reset_done',
											   'email_template_name': 'accounts/reset_password_email.html'},
												name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
														  name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
												password_reset_confirm,
												{'template_name': 'accounts/reset_password_confirm.html',
												 'post_reset_redirect': 'app:password_reset_complete'},
												  name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'},
																 name='password_reset_complete'),
	url(r'^inbox/$', views.Inbox , name='inbox'),
	url(r'^msg/(?P<pk>\d+)/$', views.Msg_View , name='msg'),
	url(r'^new_msg/$', views.New_Msg , name='new_msg'),
	url(r'^del_msg/$', views.Del_Msg , name='del_msg'),
	url(r'^read_msg/$', views.Read_Msg , name='read_msg'),
	url(r'^unread_msg/$', views.Unread_Msg , name='unread_msg'),
	url(r'^side_menu/$', views.Side_Menu , name='side_menu'),
]

financ/urls.py
from django.conf.urls import url
from . import views

app_name = 'financ'
urlpatterns = [    
	url(r'^$', views.Despesas, name="despesas"),
	url(r'^add/$', views.Despesa_Add, name='despesa_add'),
	url(r'^view/(?P<pk>\d+)/$', views.Despesa_View, name='despesa_view'),
	url(r'^edit/(?P<pk>\d+)/$', views.Despesa_Edit, name='despesa_edit'),
	url(r'^edit_all/(?P<pk>\d+)/$', views.Despesa_Edit_All, name='despesa_edit_all'),
	url(r'^del/$', views.Despesa_Del, name='despesa_del'),
	url(r'^del_all/$', views.Despesa_Del_All, name='despesa_del_all'),
	url(r'^gera_xls_mes/$', views.Gera_XLS_Mes, name='gera_xls_mes'),
	url(r'^categoria_add/$', views.Categoria_Add, name='categoria_add'),
	url(r'^categoria_list/$', views.Categoria_List, name='categoria_list'),
	url(r'^categoria_view/(?P<pk>\d+)/$', views.Categoria_View, name='categoria_view'),
	url(r'^categoria_edit/(?P<pk>\d+)/$', views.Categoria_Edit, name='categoria_edit'),
	url(r'^categoria_del/$', views.Categoria_Del, name='categoria_del'),
	url(r'^conta_add/$', views.Conta_Add, name='conta_add'),
	url(r'^conta_list/$', views.Conta_List, name='conta_list'),
	url(r'^conta_view/(?P<pk>\d+)/$', views.Conta_View, name='conta_view'),
	url(r'^conta_edit/(?P<pk>\d+)/$', views.Conta_Edit, name='conta_edit'),
	url(r'^conta_del/$', views.Conta_Del, name='conta_del'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
	url(r'^app/', include('app.urls')),
	url(r'^financ/', include('financ.urls')),
	url(r'^ponto/', include('ponto.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

financ/models.py
from django.db import models
from django.contrib.auth.models import User

class Despesa(models.Model):
	valor			= models.DecimalField(max_digits=12, decimal_places=2)	
	descricao		= models.CharField(max_length=40, blank=True)		
	dt_vencimento	= models.DateField()			
	categoria		= models.ForeignKey('Categoria', on_delete=models.PROTECT)
	pago			= models.BooleanField(default=False)
	fixa            = models.BooleanField(default=False)
	pk_fixa         = models.IntegerField(blank=True, default=0)
	usuario         = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	eliminada       = models.BooleanField(default=False)
	parcela         = models.CharField(max_length=10, blank=True)		
	importacao      = models.ForeignKey('Importacao', on_delete=models.CASCADE, null=True)
	conta           = models.ForeignKey('Conta', on_delete=models.CASCADE, blank=True, null=True)
	def __str__(self):
		return self.descricao
	class Meta:
		permissions = (('acesso_app_financ', 'Pode acessar Financeiro'),)

class Categoria(models.Model):
	descricao		= models.CharField(max_length=40)
	cor     		= models.CharField(max_length=40, blank=True)
	usuario         = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	def __str__(self):
		return self.descricao

class Conta(models.Model):
	descricao		= models.CharField(max_length=40)	
	usuario         = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	def __str__(self):
		return self.descricao

class Importacao(models.Model):
	descricao = models.CharField(max_length=40)
	dt_import = models.DateField()			
	usuario   = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	def __str__(self):
		return self.descricao

financ/forms.py
from django import forms
from django.forms.widgets import TextInput
from .models import Despesa, Categoria, Conta

class DespesaFormView(forms.ModelForm):    
	class Meta:
		model = Despesa
		fields = ('valor',
				  'descricao',	
				  'dt_vencimento',
				  'categoria',			
				  'pago',
				  'conta',
				)
		widgets = {
			'dt_vencimento': TextInput(attrs={'type': 'date'}),
		}

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super(DespesaFormView, self).__init__(*args, **kwargs)
		if user:
			self.fields['categoria'].queryset = Categoria.objects.filter(usuario=user)
			self.fields['conta'].queryset = Conta.objects.filter(usuario=user)

class CategoriaFormView(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = ('descricao',
				  'cor',
				)
		widgets = {
			'cor': TextInput(attrs={'type': 'color'}),
		}

class ContaFormView(forms.ModelForm):
	class Meta:
		model = Conta
		fields = ('descricao',)

financ/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import permission_required
from .models import (
	Despesa,
	Categoria,
	Conta,
	)
from .forms import (
	DespesaFormView,
	CategoriaFormView,
	ContaFormView,
	)
from django.contrib import messages
from .despesa import (
	AlteraDespesasPend,
	BuscaDespesasMes,
	EliminaDespesa,
	AdicionaDespesa,
	GeraExcel
	)
from mysite.decorators import user_financ
import datetime
import json

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesas(request):
	p_ano    = int(request.GET.get('year', datetime.datetime.today().year))
	p_mes    = int(request.GET.get('month', datetime.datetime.today().month))	

	try:
		current = datetime.datetime(p_ano, p_mes, 1)
	except:
		messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               
		return redirect('financ:despesas')

	if (current.month - 1) == 0:
		current = datetime.datetime(p_ano , p_mes, 1)
		next_month = datetime.datetime(p_ano, 2, 1)
		prev_month = datetime.datetime((current.year - 1), 12, 1)
	elif (current.month + 1) == 13:
		next_month = datetime.datetime((current.year + 1), 1, 1)
		prev_month = datetime.datetime(current.year, 11, 1)
	else:
		next_month = datetime.datetime(current.year, (current.month + 1), 1)
		prev_month = datetime.datetime(current.year, (current.month - 1), 1)
	mes = dict()
	mes['atual']        = current
	mes['proximo']  	= next_month
	mes['anterior'] 	= prev_month
	mes['ultdia']       = next_month - datetime.timedelta(days=1)

	despesas, totais = BuscaDespesasMes(request,current.year,current.month)

	args = {'mes': mes,
			'despesas': despesas,
			'totais': totais}

	return render(request, 'financ/despesas.html', args)

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesa_Add(request):	
	p_ano    = int(request.GET.get('year', datetime.datetime.today().year))
	p_mes    = int(request.GET.get('month', datetime.datetime.today().month))	
	current  = datetime.datetime(p_ano , p_mes, 1)
	mes = dict()
	mes['atual'] = current

	if request.method == 'POST':
		p_fixa    = bool(request.POST.get('id_repetir'))
		p_qtd_meses = request.POST.get('id_meses')

		if p_qtd_meses != '':
			qtd_meses = int(p_qtd_meses)
			if qtd_meses > 99:
				qtd_meses = 99
		else:
			qtd_meses = 2		

		form = DespesaFormView(request.POST, user=request.user)

		if form.is_valid():  
			despesa = form.save(commit=False)           	
			url = '?year=' + str(despesa.dt_vencimento.year) + '&month=' + str(despesa.dt_vencimento.month)
			despesa.fixa = p_fixa
			despesa.usuario = request.user						
			if despesa.fixa:
				despesa.parcela = '1/' + str(qtd_meses)
			despesa.save()       			   
			if despesa.fixa:
				AdicionaDespesa(despesa,qtd_meses)  
				
			messages.success(request, "Informações atualizadas com sucesso.", extra_tags='alert-success alert-dismissible')
			response = redirect('financ:despesas')

			response['Location'] += url
			return response
		else:
			messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               		
	else:
		form = DespesaFormView(user=request.user)

	args = {'form': form, 'form_categ': CategoriaFormView(), 'mes': mes}

	return render(request, 'financ/despesa_add.html', args)

@user_financ
@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesa_View(request,pk):
	p_ano    = int(request.GET.get('year', datetime.datetime.today().year))
	p_mes    = int(request.GET.get('month', datetime.datetime.today().month))	
	current  = datetime.datetime(p_ano , p_mes, 1)
	mes = dict()
	mes['atual'] = current

	despesa = get_object_or_404(Despesa, pk=pk)	
	despesa.dt_vencimento = datetime.date(p_ano,p_mes,despesa.dt_vencimento.day)

	args = {'despesa': despesa,
			'mes': mes,}

	return render(request, 'financ/despesa_view.html', args)

@user_financ
@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesa_Edit(request,pk):
	despesa = get_object_or_404(Despesa, pk=pk)

	if request.method == 'POST':
		form = DespesaFormView(request.POST, instance=despesa)        
		if form.is_valid():  
			despesa = form.save(commit=False)           	
			url = '?year=' + str(despesa.dt_vencimento.year) + '&month=' + str(despesa.dt_vencimento.month)
			despesa.save()

			messages.success(request, "Informações atualizadas com sucesso.", extra_tags='alert-success alert-dismissible')
			response = redirect('financ:despesas')

			response['Location'] += url
			return response
		else:
			messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               
	else:				
		data = {}		
		form = DespesaFormView(instance=despesa,
							   initial=data,
							   user=request.user)       		

	args = {'form': form, 'despesa': despesa, 'param': ''}    
	return render(request, 'financ/despesa_edit.html', args)

@user_financ
@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesa_Edit_All(request,pk):
	despesa = get_object_or_404(Despesa, pk=pk)

	if request.method == 'POST':
		form = DespesaFormView(request.POST, instance=despesa)        
		if form.is_valid():  
			despesa = form.save(commit=False)           	
			url = '?year=' + str(despesa.dt_vencimento.year) + '&month=' + str(despesa.dt_vencimento.month)
			despesa.save()

			AlteraDespesasPend(despesa)

			messages.success(request, "Informações atualizadas com sucesso.", extra_tags='alert-success alert-dismissible')
			response = redirect('financ:despesas')

			response['Location'] += url
			return response
		else:
			messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               
	else:				
		data = {}		
		form = DespesaFormView(instance=despesa,
							   initial=data,
							   user=request.user)       		

	args = {'form': form, 'despesa': despesa, 'param': 'all'}    
	return render(request, 'financ/despesa_edit.html', args)

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesa_Del(request):
	EliminaDespesa(request,1)
	return HttpResponse('')	

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Despesa_Del_All(request):
	EliminaDespesa(request,2)
	return HttpResponse('')	

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Categoria_Add(request):
	if request.is_ajax():
		if request.method == 'POST':
			form = CategoriaFormView(request.POST)
			if form.is_valid():
				categoria = form.save(commit=False)           	
				categoria.usuario = request.user
				categoria.save()
				retorno_dict = {'chave': categoria.pk, 'descricao': categoria.descricao}				
			else:
				retorno_dict = {'chave': 'erro', 'descricao': str(form.errors)}

			retorno = json.dumps(retorno_dict)
			return HttpResponse(retorno)
		
	else:	
		if request.method == 'POST':
			form = CategoriaFormView(request.POST)
			if form.is_valid():
				categoria = form.save(commit=False)           	
				categoria.usuario = request.user
				categoria.save()
				return redirect('financ:categoria_list')
		else:
			form = CategoriaFormView()

		args = {'form': form}

		return render(request, 'financ/categoria_add.html', args)

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Categoria_List(request):	
	categorias = Categoria.objects.filter(usuario=request.user)	
	args = {'categorias': categorias}
	return render(request, 'financ/categoria_list.html', args)

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Categoria_View(request, pk):
	categoria = get_object_or_404(Categoria, pk=pk)
	if categoria.usuario != request.user:
		messages.error(request, "Acesso negado!", extra_tags='alert-error alert-dismissible')			
		return redirect('financ:categoria_list')

	args = {'categoria': categoria}
	return render(request, 'financ/categoria_view.html', args)

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Categoria_Edit(request, pk):
	categoria = get_object_or_404(Categoria, pk=pk)
	if categoria.usuario != request.user:
		messages.error(request, "Acesso negado!", extra_tags='alert-error alert-dismissible')			
		return redirect('financ:categoria_list')
	if request.method == 'POST':
		form = CategoriaFormView(request.POST, instance=categoria)        
		if form.is_valid():  			
			form.save()            
			messages.success(request, "Informações atualizadas com sucesso.", extra_tags='alert-success alert-dismissible')
			return redirect('financ:categoria_list')
		else:
			messages.error(request, "Foram preenchidos dados incorretamente.", extra_tags='alert-error alert-dismissible')               
	else:
		form = CategoriaFormView(instance=categoria)

	args = {'form': form}
	return render(request, 'financ/categoria_edit.html', args)

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Categoria_Del(request):
	if request.POST and request.is_ajax():
		if request.POST.getlist('categoria_lista[]'):
			categoria_list = request.POST.getlist('categoria_lista[]')
			for i in categoria_list:
				categoria = Categoria.objects.get(pk=i)
				if categoria.usuario != request.user:
					messages.error(request, "Acesso negado!", extra_tags='alert-error alert-dismissible')
					return redirect('financ:categoria_list')
				categoria.delete()
			messages.success(request, "Mensagens excluidas com sucesso.", extra_tags='alert-success alert-dismissible')
		else:
			messages.error(request, "Nenhuma mensagem selecionada.", extra_tags='alert-error alert-dismissible')
	return HttpResponse('')

@permission_required('financ.acesso_app_financ', raise_exception=True)
def Conta_Add(request):	
	if request.method == 'POST':
		form = ContaFormView(request.POST)
		if form.is_valid():
			conta = form.save(commit=False)           	
			conta.usuario = request.user
			conta.save()

financ/templates/financ/conta_view.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Conta
        <small>Detalhe</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            
            <a class="btn btn-default" href="{% url 'financ:conta_list' %}">Voltar</a>
            <a class="btn btn-default" href="{% url 'financ:conta_edit' pk=conta.pk %}">Editar</a>
            <a id="bt-del" class="btn btn-default" 
               data-toggle="confirmation" data-placement="bottom"
               data-btn-ok-label="Confirmar" data-btn-ok-icon="glyphicon glyphicon-share-alt"
               data-btn-ok-class="btn-success"
               data-btn-cancel-label="Cancelar" data-btn-cancel-icon="glyphicon glyphicon-ban-circle"
               data-btn-cancel-class="btn-danger"
               data-title="Tem certeza?" data-content="A conta será excluida permanentemente.">Deletar </a>
            <p></p>       
            <table class="table" style="max-width:300px;">  {% csrf_token %}
                <tr>
                    <th>Descrição</th>
                    <td>{{ conta.descricao }}</td>
                </tr>                
            </table>            
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    $('#bt-del').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        onConfirm: function () {
            var conta_list = [];        
            conta_list.push({{ conta.pk }});
            $.ajax({
                url:"{% url 'financ:conta_del' %}",
                type: "POST",            
                data: {conta_lista: conta_list, csrfmiddlewaretoken: '{{ csrf_token }}'},
                success:function(response){
                window.location.href= "{% url 'financ:conta_list' %}"
                },
                complete:function(){},
                error:function (xhr, textStatus, thrownError){}
            });
        }
    });    

</script>
{% endblock javascript %}

financ/templates/financ/despesa_edit.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Despesa
        {% if param == 'all' %}
            <small>Editando todas não pagas</small>
        {% else %}
            <small>Editando somente esta</small>
        {% endif %}

    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            <form method="POST">
                <table class="table" style="max-width:500px;">  {% csrf_token %}
                    {{ form.as_table }}                    
                </table>
                <button class="btn btn-default" type="submit">Salvar</button>
                <a class="btn btn-default" href="{% url 'financ:despesa_view' pk=despesa.pk %}?year={{ despesa.dt_vencimento|date:"Y"  }}&month={{ despesa.dt_vencimento|date:"m" }}">Cancelar</a>
            </form>
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    {% if param == 'all' %}
        $("#id_dt_vencimento").prop("readonly", true);        
        $("#id_pago").closest("tr").hide()  
    {% endif %}

    $('#id_categoria').selectpicker({          
        size: 5,
        width: 'fit',
        //showTick: true,
    });
    $('#id_conta').selectpicker({          
        size: 5,
        width: 'fit',
        //showTick: true,
    });

</script>
{% endblock javascript %}

financ/templates/financ/despesa_view.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Despesa
        <small>Detalhe</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    
    <div class="box box-default">            
        <div class="box-body">             
            <div class="modal fade" tabindex="-1" role="dialog" id="div-del">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">Tem certeza que deseja excluir ?</h4>
                        </div>
                        <div class="modal-body">                            
                            <a class="btn btn-default btn-del-ok" id="bt-confirm-del" data-dismiss="modal" aria-label="Close"><span class="fa fa-check"></span></a>                        
                            <a class="btn btn-default btn-del-cancel" data-dismiss="modal" aria-label="Close"><span class="fa fa-times"></span></a>
                        </div>                        
                    </div>
                </div>
            </div>            
            <div class="modal fade" tabindex="-1" role="dialog" id="div-del-all">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">Tem certeza que deseja excluir todas despesas pendentes ?</h4>
                        </div>
                        <div class="modal-body">                            
                            <a class="btn btn-default btn-del-ok" id="bt-confirm-del-all" data-dismiss="modal" aria-label="Close"><span class="fa fa-check"></span></a>                        
                            <a class="btn btn-default btn-del-cancel" data-dismiss="modal" aria-label="Close"><span class="fa fa-times"></span></a>
                        </div>                        
                    </div>
                </div>
            </div>            
            <div class="btn-group" role="group" aria-label="...">
                <a type="button" class="btn btn-default" href="{% url 'financ:despesas' %}?year={{ despesa.dt_vencimento|date:"Y"  }}&month={{ despesa.dt_vencimento|date:"m" }}">Voltar</a>                
                {% if despesa.fixa == False and despesa.pk_fixa == 0 or despesa.pago == True %}
                    <a type="button" class="btn btn-default" href="{% url 'financ:despesa_edit' pk=despesa.pk %}?year={{ mes.atual|date:"Y"  }}&month={{ mes.atual|date:"m" }}">Editar</a>
                    <a type="button" class="btn btn-default" href="" data-toggle="modal" data-target="#div-del">Deletar</a>

                {% else %}
                    <div class="btn-group" role="group">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            Editar
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{% url 'financ:despesa_edit' pk=despesa.pk %}?year={{ mes.atual|date:"Y"  }}&month={{ mes.atual|date:"m" }}&fixa=1">Somente esta</a></li>
                            <li><a href="{% url 'financ:despesa_edit_all' pk=despesa.pk %}?year={{ mes.atual|date:"Y"  }}&month={{ mes.atual|date:"m" }}&fixa=2">Todas não pagas</a></li>                    
                        </ul>
                    </div>
                    <div class="btn-group" role="group">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            Deletar
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li>                            
                                <a href="" data-toggle="modal" data-target="#div-del">Somente esta</a>
                            </li>
                            <li>
                                <a href="" data-toggle="modal" data-target="#div-del-all">Todas não pagas</a>
                            </li>                    
                        </ul>
                    </div>
                {% endif %}                                
            </div>
            <p/>

            <table class="table" style="max-width:500px;">
                <tr>
                    <th>Valor</th>
                    <td>{{ despesa.valor }}</td>
                </tr>
                <tr>
                    <th>Descrição</th>
                    <td>{{ despesa.descricao }}</td>
                </tr>
                <tr>
                    <th>Categoria</th>
                    <td>{{ despesa.categoria.descricao }}</td>
                </tr>
                <tr>
                    <th>Vencimento</th>
                    <td>{{ despesa.dt_vencimento }}</td>
                </tr>
                <tr>
                    <th>Pago?</th>
                    <td>{{ despesa.pago }}</td>
                </tr>
                <tr>
                    <th>Conta</th>
                    <td>{{ despesa.conta }}</td>
                </tr>

            </table>            
        </div>
    </div>

</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    $('#bt-confirm-del').click(function(e) {
        var despesa_list = [];        
        despesa_list.push({{ despesa.pk|stringformat:"0.f" }});
        $.ajax({
            url:"{% url 'financ:despesa_del' %}?year={{ despesa.dt_vencimento|date:"Y"  }}&month={{ despesa.dt_vencimento|date:"m" }}",
            type: "POST",            
            data: {despesa_lista: despesa_list, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success:function(response){
            window.location.href= "{% url 'financ:despesas' %}?year={{ despesa.dt_vencimento|date:"Y"  }}&month={{ despesa.dt_vencimento|date:"m" }}"
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });        
    });   

    $('#bt-confirm-del-all').click(function(e) {
        var despesa_list = [];        
        despesa_list.push({{ despesa.pk_fixa|stringformat:"0.f" }});
        $.ajax({
            url:"{% url 'financ:despesa_del_all' %}?year={{ despesa.dt_vencimento|date:"Y"  }}&month={{ despesa.dt_vencimento|date:"m" }}",
            type: "POST",            
            data: {despesa_lista: despesa_list, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success:function(response){
            window.location.href= "{% url 'financ:despesas' %}?year={{ despesa.dt_vencimento|date:"Y"  }}&month={{ despesa.dt_vencimento|date:"m" }}"
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });        
    });   

</script>
{% endblock javascript %}