app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
	login,
	logout,
	password_reset,
	password_reset_done,
	password_reset_confirm,
	password_reset_complete,
	)

from . import views

app_name = 'app'
urlpatterns = [
	url(r'^$', views.Home, name='home'),
	url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
	url(r'^profile/$', views.Profile , name='profile'),
	url(r'^profile/edit/$', views.Edit_profile , name='edit_profile'),
	url(r'^profile/editpic/$', views.Edit_profilepic , name='edit_profilepic'),
	url(r'^register/$', views.Register , name='register'),
	url(r'^change-password/$', views.Change_Password , name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html',
											   'post_reset_redirect': 'app:password_reset_done',
											   'email_template_name': 'accounts/reset_password_email.html'},
												name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
														  name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
												password_reset_confirm,
												{'template_name': 'accounts/reset_password_confirm.html',
												 'post_reset_redirect': 'app:password_reset_complete'},
												  name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'},
																 name='password_reset_complete'),
	url(r'^inbox/$', views.Inbox , name='inbox'),
	url(r'^msg/(?P<pk>\d+)/$', views.Msg_View , name='msg'),
	url(r'^new_msg/$', views.New_Msg , name='new_msg'),
	url(r'^del_msg/$', views.Del_Msg , name='del_msg'),
	url(r'^read_msg/$', views.Read_Msg , name='read_msg'),
	url(r'^unread_msg/$', views.Unread_Msg , name='unread_msg'),
	url(r'^side_menu/$', views.Side_Menu , name='side_menu'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
	url(r'^app/', include('app.urls')),
	url(r'^financ/', include('financ.urls')),
	url(r'^ponto/', include('ponto.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

app/templates/accounts/change_password.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Senha
        <small>Altera senha de acesso</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">
            <form method="post">
				{% csrf_token %}
				<table class="table">
					{{ form.as_table }}
				</table>
				<button class="btn btn-primary" type="submit">Salvar</button>
				<a class="btn btn-primary" href="{% url 'app:profile' %}">Voltar</a>
			</form>
        </div>
    </div>                    
</section><!-- /.content -->	

{% endblock %}

app/templates/accounts/edit_profile.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Perfil
        <small>Edita Informações</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">
            <form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<table class="table table-hover">
					  {{ user_form.as_table }}
                      {{ profile_form.as_table }}
				</table>
				<button class="btn btn-primary" type="submit">Salvar</button>
				<a class="btn btn-primary" href="{% url 'app:profile' %}">Voltar</a>
			</form>
        </div>
    </div>                    
</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">    
    jQuery(document).ready(function(){                
        $("#id_password").closest('tr').hide();
    });    

</script>
{% endblock javascript %}

app/templates/accounts/edit_profilepic.html
{% extends 'app/base.html' %}

{% block content %}

<head>    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/plugins/profilepic/assets/css/profile-picture.css' %}">
    <style>
        .preview {
            margin: 10px;
            display: none;
        }
        .preview--rounded {
            width: 160px;
            height: 160px;
            border-radius: 50%;
        }
    </style>
</head>


<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Perfil
        <small>Edita Foto</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}				
                <div class="profile">
                    <div class="photo">
                        <input type="file" accept="image/*">
                        <div class="photo__helper">
                            <div class="photo__frame photo__frame--circle">
                                <canvas class="photo__canvas"></canvas>
                                <div class="message is-empty">
                                    <p class="message--desktop">Drop your photo here or browse your computer.</p>
                                    <p class="message--mobile">Tap here to select your picture.</p>
                                </div>
                                <div class="message is-loading">
                                    <i class="fa fa-2x fa-spin fa-spinner"></i>
                                </div>
                                <div class="message is-dragover">
                                    <i class="fa fa-2x fa-cloud-upload"></i>
                                    <p>Drop your photo</p>
                                </div>
                                <div class="message is-wrong-file-type">
                                    <p>Only images allowed.</p>
                                    <p class="message--desktop">Drop your photo here or browse your computer.</p>
                                    <p class="message--mobile">Tap here to select your picture.</p>
                                </div>
                                <div class="message is-wrong-image-size">
                                    <p>Your photo must be larger than 150px.</p>
                                </div>
                            </div>
                        </div>

                        <div class="photo__options hide">
                            <div class="photo__zoom">
                                <input type="range" class="zoom-handler">
                            </div><a href="javascript:;" class="remove"><i class="fa fa-trash"></i></a>
                        </div>
                    </div>
                </div>                
                <hr>                				
                <button class="btn btn-primary" type="button" id="previewBtn">Preview</button>
				<button id="uploadBtn" class="btn btn-primary" type="button">Salvar</button>
				<a class="btn btn-primary" href="{% url 'app:profile' %}">Voltar</a>
                <hr>                                
                <img src="" alt="" class="preview preview--rounded">
			</form>
        </div>
    </div>                    
</section><!-- /.content -->	

{% endblock %}

{% block javascript %}
<script src="{% static 'app/plugins/profilepic/scripts/profile-picture.js' %}"></script>    
<script type="text/javascript">        
    $('#previewBtn').on('click', function() {
        $('.preview').show().attr('src',pp.getAsDataURL());  
    });

    var pp = new profilePicture('.profile', '{% if profile.foto_perfil %}{{ profile.foto_perfil.url }}{% endif %}',
    {
        onLoad: function (type) {
            $('.preview').hide().attr('src','');
        },
        onChange: printOutput,
        onRemove: function (type) {
            $('.preview').hide().attr('src','');
        },
        onError: function (type) {
            console.log('Error type: ' + type);
        }
    });    

    function printOutput(data) {
        //console.log(data);
    }

    $('#uploadBtn').on('click', function() {
        if ($('.photo').hasClass('photo--empty')) {
            image = null;
        }
        else{
            image = pp.getAsDataURL();
        }       
        
        $.post("{% url 'app:edit_profilepic' %}", { image: image, csrfmiddlewaretoken: '{{ csrf_token }}'})
         .done(function() {
            window.location.href = "{% url 'app:profile' %}"
        });        
    });


</script>
{% endblock javascript %}

app/templates/accounts/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Login</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />        
        


    </head>

    <body class="login-page">
		<div class="login-box">
		    <div class="login-box-body">
		        <h1 class="text-center">Login</h1>                
		        <div class="modal-body">
		            <form method="post">{% csrf_token %}
		            	<table class="table table-hover alinhamento">
		                	{{ form.as_table }}
		                </table>
		                <div class="form-group">                            
		                    <input type="submit" class="btn btn-primary btn-lg btn-block" name="login" value="Login" />
		                </div>       
		            </form>            
		            <ul class="">
			            <li><a href="{% url 'app:register' %}">Registrar</a></li>   
			            <li><a href="{% url 'app:reset_password' %}">Esqueceu a senha?</a></li>   
			        </ul>
		        </div>
		    </div>
		</div>
	</body>
</html>

app/templates/accounts/logout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Logout</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />        
        


    </head>


    <body class="login-page">
		<div class="login-box">
		    <div class="login-box-body">
		        <h1 class="text-center">Você foi desconectado</h1>                
		        <div class="modal-body">		            
		            <ul class="">
			            <li><a href="{% url 'app:login' %}">Logar novamente</a></li>   
			            <li><a href="{% url 'app:register' %}">Registrar</a></li>   
			            <li><a href="{% url 'app:reset_password' %}">Esqueceu a senha?</a></li>   
			        </ul>
		        </div>
		    </div>
		</div>
	</body>
</html>		  

app/templates/accounts/profile.html
{% extends 'app/base.html' %}

{% block content %}
<head>
    {% load static %}        
    <style>
        .preview {
            margin: 20px 0 10px 0;            
        }
        .preview--rounded {
            width: 160px;
            height: 160px;
            border-radius: 50%;
        }
        .imagem_perfil{
            text-align: center;                            
        }
        .glyphicon{
            font-size: 22px;
        }
        .texto_user p {
            margin-top:10px;
            font-size:16px;

        }
        td{              
            font-size: 16px;   
            vertical-align: middle;
            padding-left: 10px;
            padding-top:5px;
        }        
    </style>
</head>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Perfil
        <small>Consulta Informações</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">
            <div class="row">
                <div class="col-md-4 col-sm-6 col-xs-12 imagem_perfil" style="max-width:200px;">                
                    {% if profile.foto_perfil %}
                        <img src="{{ profile.foto_perfil.url }}" class="preview preview--rounded">
                    {% else %}
                        <img src="{% static 'img/img-user.jpg' %}" class="preview preview--rounded">
                    {% endif %}                            
                    <a href="{% url 'app:edit_profilepic' %}">Alterar Imagem</a>                     
                    
                </div>
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                    <div class="texto_user">
                        <table>
                            <tr><td><i class="glyphicon glyphicon-user"></i></td><td>{{ user }}</td></tr>
                            <tr><td><i class="glyphicon glyphicon-envelope"></i></td><td>{{ user.email }}</td></tr>
                            <tr><td><i class="glyphicon glyphicon-gift"></i></td><td>{{ profile.dt_nascimento }}</td></tr>
                            <tr><td><i class="glyphicon glyphicon-map-marker"></i></td><td>{{ profile.cidade }} - {{ profile.estado }}</td></tr>
                        </table>                        
                        <p>{{ profile.descricao }}</p>
                    </div>

                </div>
            </div>
            <hr>
            <a class="btn btn-default" href="{% url 'app:edit_profile' %}">Editar Perfil</a>
            <a class="btn btn-default" href="{% url 'app:change_password' %}">Alterar Senha</a>                     

        </div>
    </div>                    
</section><!-- /.content -->	

{% endblock %}

app/templates/accounts/register.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Registrar</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />        
        


    </head>


    <body class="register-page">
		<div class="container">
		    <div class="box box-primary">
		        <h2 class="text-center">Registrar</h2>
		        <div class="modal-body">		
		        	<form method="POST">
						{% csrf_token %}
						<table class="table table-hover">
							{{ form.as_table }}
						</table>
						<button type="submit" class="btn btn-primary">Registrar</button>
						<a class="btn btn-primary" href="{% url 'app:login' %}">Voltar</a>
					</form>            		            
		        </div>
		    </div>
		    
		
	</body>
</html>		  

app/templates/accounts/reset_password.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Reset Senha</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />
    </head>

    <body class="register-page">
        <div class="container">
            <div class="box box-primary">
                <h2 class="text-center">Resetar senha</h2>
                <div class="modal-body">
                    <p>Esqueceu sua senha? Informe o email registrado para seu usuario e siga as instruções.</p>
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table table-hover">
                            {{ form.as_table }}
                        </table>
                        <!--<p style="color:red;font-size:18px;">Função desabilitada temporariamente, favor entre em contato com o Administrador.</p>-->
                        <button type="submit" class="btn btn-primary">Enviar</button>
                        <a class="btn btn-primary" href="{% url 'app:login' %}">Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/accounts/reset_password_complete.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Reset Senha</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />        
        


    </head>


    <body class="register-page">
		<div class="container">
		    <div class="box box-primary">
		        <h2 class="text-center">Senha alterada com sucesso!</h2>
		        <div class="modal-body">		
		        	<p>Agora você já pode realizar o login utilizando a nova senha.</p>
		        	
					<a class="btn btn-primary" href="{% url 'app:login' %}">Login</a>
					
		        </div>
		    </div>
		    
		
	</body>
</html>		  

app/templates/accounts/reset_password_confirm.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Reset Senha</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />        
        


    </head>


    <body class="register-page">
		<div class="container">
		    <div class="box box-primary">
		        <h2 class="text-center">Informe a nova senha</h2>
		        <div class="modal-body">				        	
		        	<form method="POST">
						{% csrf_token %}
						<table class="table table-hover">
							{{ form.as_table }}
						</table>
						<button type="submit" class="btn btn-primary">Salvar</button>
						<a class="btn btn-primary" href="{% url 'app:login' %}">Voltar</a>
					</form>            		            
		        </div>
		    </div>
		    
		
	</body>
</html>		  

app/templates/accounts/reset_password_done.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">

        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

        {% block title %}
            <title>Reset Senha</title>
        {% endblock title %}

        {% load static %}
        <!-- Bootstrap 3.3.4 -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/bootstrap/css/bootstrap.css' %}" />
        <!-- Theme style -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/AdminLTE.css' %}" />
        <!-- CSS TEMPLATE -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
        <!-- CSS Tema azul -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/dist/css/skins/skin-black-light.css' %}" />        
        <!-- Font Awesome Icons -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/font-awesome/css/font-awesome.min.css' %}" />        
        


    </head>


    <body class="register-page">
		<div class="container">
		    <div class="box box-primary">
		        <h2 class="text-center">Email enviado com sucesso!</h2>
		        <div class="modal-body">		
		        	<p>Favor acessar seu email e seguir com as instruções.</p>					
                    <a class="btn btn-primary" href="{% url 'app:login' %}">Voltar</a>
		        </div>
		    </div>
		    
		
	</body>
</html>		  

app/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'app:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}