app/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
	login,
	logout,
	password_reset,
	password_reset_done,
	password_reset_confirm,
	password_reset_complete,
	)

from . import views

app_name = 'app'
urlpatterns = [
	url(r'^$', views.Home, name='home'),
	url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
	url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
	url(r'^profile/$', views.Profile , name='profile'),
	url(r'^profile/edit/$', views.Edit_profile , name='edit_profile'),
	url(r'^profile/editpic/$', views.Edit_profilepic , name='edit_profilepic'),
	url(r'^register/$', views.Register , name='register'),
	url(r'^change-password/$', views.Change_Password , name='change_password'),
	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html',
											   'post_reset_redirect': 'app:password_reset_done',
											   'email_template_name': 'accounts/reset_password_email.html'},
												name='reset_password'),
	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
														  name='password_reset_done'),
	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
												password_reset_confirm,
												{'template_name': 'accounts/reset_password_confirm.html',
												 'post_reset_redirect': 'app:password_reset_complete'},
												  name='password_reset_confirm'),
	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'},
																 name='password_reset_complete'),
	url(r'^inbox/$', views.Inbox , name='inbox'),
	url(r'^msg/(?P<pk>\d+)/$', views.Msg_View , name='msg'),
	url(r'^new_msg/$', views.New_Msg , name='new_msg'),
	url(r'^del_msg/$', views.Del_Msg , name='del_msg'),
	url(r'^read_msg/$', views.Read_Msg , name='read_msg'),
	url(r'^unread_msg/$', views.Unread_Msg , name='unread_msg'),
	url(r'^side_menu/$', views.Side_Menu , name='side_menu'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

urlpatterns = [
	url(r'^app/', include('app.urls')),
	url(r'^financ/', include('financ.urls')),
	url(r'^ponto/', include('ponto.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import os

class Profile(models.Model):
	user 			= models.OneToOneField(User, on_delete=models.CASCADE)
	descricao 		= models.TextField(max_length=500, blank=True)
	cidade 			= models.CharField(max_length=30, blank=True)
	estado 			= models.CharField(max_length=2, blank=True)
	dt_nascimento 	= models.DateField(null=True, blank=True)
	foto_perfil     = models.FileField(upload_to='perfil/', blank=True, null=True)
	layoutskin      = models.ForeignKey('LayoutSkin', on_delete=models.SET_DEFAULT, default=1)

	def ApagaFoto(self):
		self.foto_perfil = None
		self.save()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

##########  deletar foto do perfil antiga ##########
@receiver(models.signals.post_delete, sender=Profile)
def delete_file_on_del_profile(sender, instance, **kwargs):    
	if instance.foto_perfil:
		if os.path.isfile(instance.foto_perfil.path):
			os.remove(instance.foto_perfil.path)

@receiver(models.signals.pre_save, sender=Profile)
def delete_file_on_change_profile(sender, instance, **kwargs):    
	if not instance.pk:
		return False

	try:
		old_file = Profile.objects.get(pk=instance.pk).foto_perfil
	except Profile.DoesNotExist:
		return False

	new_file = instance.foto_perfil
	if not old_file == new_file:
		if old_file:
			if os.path.isfile(old_file.path):
				os.remove(old_file.path)
######################################################

class Mensagem(models.Model):
	destinatario	= models.ForeignKey(User, on_delete=models.CASCADE)
	remetente  		= models.CharField(max_length=30, blank=True)
	assunto         = models.CharField(max_length=30, blank=True)
	mensagem   		= models.TextField(max_length=500, blank=True)
	dt_mensagem 	= models.DateTimeField(null=True, blank=True)
	lida            = models.BooleanField(default=False)

	def Lida(self, param):
		self.lida = param
		self.save()

	def __str__(self):
		return self.assunto


class LayoutSkin(models.Model):
	descricao       = models.TextField(max_length=40, blank=True)
	nome_css        = models.TextField(max_length=40, blank=True)
	def __str__(self):
		return self.descricao

app/templates/app/inbox.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Inbox
        <small>Mensagens</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">                      
            <div class="table-responsive">                                                   
                
                <nav class="navbar navbar-default">
                    <div class="container-fluid">                    

                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                          <a class="navbar-brand" href="#">Mensagens</a>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <form class="navbar-form navbar-right" method="GET">                                
                                <div class="form-group">                                                            
                                    <small>Registros por pag.</small>
                                    <select class="input-sm"  id="reg_pag" name="reg_pag">                
                                        <option value="10">10</option>                                    
                                        <option value="20">20</option>                                    
                                        <option value="50">50</option>                                    
                                        <option value="100">100</option>                
                                    </select>                                           
                                </div>                       
                                <div class="form-group">                            
                                    <small>Ordenar por:</small>
                                    <select class="input-sm"  id="ordenar" name="ordenar">                
                                        <option value="-dt_mensagem">Data</option>
                                        <option value="assunto">Assunto</option>
                                        <option value="remetente">Remetente</option>                                                        
                                    </select>                                                  
                                </div>                        
                                <div class="form-group">              
                                    <input class="input-sm" pattern="[a-zA-Z0-9]+" type="text" id="buscar" name="buscar" value='{{ filtro.filtro1 }}' placeholder="Buscar...">
                                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                                </div>                        
                            </form>                                                                                                     
                        </div>                                                                        
                    </div>
                </nav>
                <table>
                    <tr>
                        <td>
                            <a type="button" class="btn btn-default btn-sm checkbox-toggle btn-selec-all"><span class="selec-all" value="false"><i class="fa fa-square-o"></i></span></a>                
                            <a href="{% url 'app:new_msg' %}" type="button" class="btn btn-default btn-sm"><i class="fa fa-file-o" aria-hidden="true"></i></i></a>
                            <a id="bt-del" href="" type="button" class="btn btn-default btn-sm"                                
                               data-toggle="confirmation" data-placement="bottom"
                               data-btn-ok-label="Confirmar" data-btn-ok-icon="glyphicon glyphicon-share-alt"
                               data-btn-ok-class="btn-success"
                               data-btn-cancel-label="Cancelar" data-btn-cancel-icon="glyphicon glyphicon-ban-circle"
                               data-btn-cancel-class="btn-danger"
                               data-title="Tem certeza?" data-content="A mensagem será excluida permanentemente."><i class="fa fa-trash-o"></i></a>
                            <a href="{% url 'app:inbox' %}" type="button" class="btn btn-default btn-sm"><i class="fa fa-refresh"></i></a>
                        </td>
                        <td>&nbsp;</td>
                        <td>                            
                            <div class="dropdown">
                                <button href="#" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a id="bt-lido" href="#">Marcar como lido</a></li>
                                    <li><a id="bt-nao-lido" href="#">Marcar como não lido</a></li>                                    
                                </ul>
                            </div>      
                        </td>
                    </tr>
                </table>          
                <p/>
                <div class="table-responsive">
                    <table class="table table-selectable-multiple" style="width: 100%;">                    
                        {% for msg in mensagem %}
                            {% if msg.lida == False %}
                            <tr class="linhainbox" style="font-weight:bold" id="{{ msg.pk }}">
                            {% else %}
                            <tr class="linhainbox" id="{{ msg.pk }}">
                            {% endif %}                           
                                <td class="checkboxinbox" align="center" style="width:45px;"><input type="checkbox"></td>
                                <td class="colunainbox">{{ msg.remetente | slice:":10"  }}</td>
                                <td class="colunainbox">{{ msg.assunto | slice:":25"  }} <span style="color:gray;"> - {{ msg.mensagem | slice:":60" }}</span></td>
                                <td align="right" class="colunainbox">{{ msg.dt_mensagem }}</td>
                            </tr>                    
                        {% endfor %}
                    </table>
                </div>
            </div>

            <ul class="pagination">
                {% if mensagem.has_previous %}
                    <li><a href="{{ filtro.url }}&page=1"><span class="fa fa-angle-double-left"></span></a></li>
                    <li><a href="{{ filtro.url }}&page={{ mensagem.previous_page_number }}"><span class="fa fa-angle-left"></span></a></li>
                {% else %}
                    <li class="disabled"><span class="fa fa-angle-double-left"></span></li>
                    <li class="disabled"><span class="fa fa-angle-left"></span></li>
                {% endif %}
                {% for page in mensagem.paginator.page_range %}
                    {% if page >= mensagem.number|add:"-3" and page < mensagem.number %}
                        <li><a href="{{ filtro.url }}&page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                    {% ifequal mensagem.number page %}
                        <li class="active"><span>{{ mensagem.number }}</span></li>
                    {% endifequal %}                    
                    {% if page <= mensagem.number|add:"3" and page > mensagem.number %}
                        <li><a href="{{ filtro.url }}&page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if mensagem.has_next %}
                    <li><a href="{{ filtro.url }}&page={{ mensagem.next_page_number }}"><span class="fa fa-angle-right"></span></a></li>
                    <li><a href="{{ filtro.url }}&page={{ mensagem.paginator.num_pages }}"><span class="fa fa-angle-double-right"></span></a></li>
                {% else %}
                    <li class="disabled"><span class="fa fa-angle-right"></span></li>      
                    <li class="disabled"><span class="fa fa-angle-double-right"></span></li>
                {% endif %}                
            </ul>
                       
        </div>
    </div>               
</section><!-- /.content -->	

{% endblock %}

{% block javascript %}
<script type="text/javascript">    
    
    $(document).ready(function(){
        
    });    
    $('#bt-del').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        onConfirm: function () {
            var msgs_lista = [];        
            $(".selected").each(function(index) {                        
                msgs_lista.push($(this).attr('id'));             
            });        
            $.ajax({
                url:"{% url 'app:del_msg' %}",
                type: "POST",            
                data: {msgs_list: msgs_lista, csrfmiddlewaretoken: '{{ csrf_token }}'},
                success:function(response){
                window.location.href= "{% url 'app:inbox' %}"
                },
                complete:function(){},
                error:function (xhr, textStatus, thrownError){}
            });
        }
    });
    $("#bt-lido").click(function(e){
        e.preventDefault();
        var msgs_lista = [];
        $(".selected").each(function(index) {                        
            msgs_lista.push($(this).attr('id'));             
        });        
        $.ajax({
            url:"{% url 'app:read_msg' %}",
            type: "POST",            
            data: {msgs_list: msgs_lista, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success:function(response){
                window.location.reload();
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });
    });
    $("#bt-nao-lido").click(function(e){
        e.preventDefault();
        var msgs_lista = [];
        $(".selected").each(function(index) {                        
            msgs_lista.push($(this).attr('id'));             
        });        
        $.ajax({
            url:"{% url 'app:unread_msg' %}",
            type: "POST",            
            data: {msgs_list: msgs_lista, csrfmiddlewaretoken: '{{ csrf_token }}'},
            success:function(response){
                window.location.reload();
            },
            complete:function(){},
            error:function (xhr, textStatus, thrownError){}
        });
    });


    $(".colunainbox").click(function(e) {
      window.location.href = "/app/msg/" + $(this).closest("tr").attr("id") + "/";
    });    
    $(".checkboxinbox").click(function(e) {      
      if ($(this).closest("tr").hasClass("selected")) {
        $(this).closest("tr").removeClass("selected");
        $(this).closest("tr")
          .find("input[type='checkbox']")
          .prop("checked", false);
      } else {
        $(this).closest("tr").addClass("selected");
        $(this).closest("tr")
          .find("input[type='checkbox']")
          .prop("checked", true);
      }
    });
    $(".btn-selec-all").click(function(e) {
        valor = $(this).val();
        $(this).val(!valor);
        if ($(this).val() == true){
            $(".selec-all")[0].innerHTML = "<i class='fa fa-check-square-o'></i>";                              

            $(".linhainbox").each(function( index ) {
                $(this).addClass("selected");
                $(this).find("input[type='checkbox']").prop("checked", true);
            });             
            
        }
        else{
            $(".selec-all")[0].innerHTML = "<i class='fa fa-square-o'></i>";      
            $(".checkboxinbox").trigger('click');

            $(".linhainbox").each(function( index ) {
                $(this).removeClass("selected");
                $(this).find("input[type='checkbox']").prop("checked", false);
            });            
        }      
    });

    $('#reg_pag').val('{{ filtro.pag }}'); 
    $('#ordenar').val('{{ filtro.ordenar }}'); 
    $('#buscar').val('{{ filtro.buscar }}');     

</script>
{% endblock javascript %}

app/templates/app/message_detail.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Inbox
        <small>Mensagens</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">          
            <a href="{% url 'app:inbox' %}" class="btn btn-default">Inbox </a>
            <a id="bt-del" class="btn btn-default" 
               data-toggle="confirmation" data-placement="bottom"
               data-btn-ok-label="Confirmar" data-btn-ok-icon="glyphicon glyphicon-share-alt"
               data-btn-ok-class="btn-success"
               data-btn-cancel-label="Cancelar" data-btn-cancel-icon="glyphicon glyphicon-ban-circle"
               data-btn-cancel-class="btn-danger"
               data-title="Tem certeza?" data-content="A mensagem será excluida permanentemente.">Deletar </a>
            <p></p>
            De: {{ msg.remetente }}<br>
            {{ msg.dt_mensagem }}<br>
            <h4>Assunto: {{ msg.assunto }}</h4>
            <div class="form-group">              
              <textarea class="form-control" rows="10" id="comment">{{ msg.mensagem }}</textarea>
            </div>            
                       
        </div>
    </div>               
</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">        

    $('#bt-del').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        onConfirm: function () {
            var msgs_lista = [];        
            msgs_lista.push({{ msg.pk }});
            $.ajax({
                url:"{% url 'app:del_msg' %}",
                type: "POST",            
                data: {msgs_list: msgs_lista, csrfmiddlewaretoken: '{{ csrf_token }}'},
                success:function(response){
                window.location.href= "{% url 'app:inbox' %}"
                },
                complete:function(){},
                error:function (xhr, textStatus, thrownError){}
            });
        }
    });

</script>
{% endblock javascript %}

app/templates/app/new_message.html
{% extends 'app/base.html' %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Inbox
        <small>Mensagens</small>
    </h1>                    
</section>

<!-- Main content -->
<section class="content">
    <!-- Your Page Content Here -->                    

    <div class="box box-primary">            
        <div class="box-body">           
            <form method="POST"> {% csrf_token %}
                <table class="table table-hover">
                    <tr><td></td><td><input class="check-todos" type="checkbox" name="todos"> Todos </input></td></tr>
                    {{ form.as_table }}
                </table>      
                
                <button type="submit" class="btn btn-default">Enviar </button>
                <a href="{% url 'app:inbox' %}" class="btn btn-default">Voltar </a>
            </form>                       
        </div>
    </div>               
</section><!-- /.content -->	

{% endblock %}

{% block javascript %}

<script type="text/javascript">    
    jQuery(document).ready(function(){                
        $("#id_destinatario").selectpicker({
            size: 5,
            width: 'fit',
            liveSearch: true,
        });                    
    });
    $(".check-todos").click(function(e){        
        $("#id_destinatario").val({{ request.user.id }});
        $("#id_destinatario").selectpicker("refresh");           
        if($("#id_destinatario").closest('tr').css("display")!="none"){
            $("#id_destinatario").closest('tr').attr("style", "display:none");
        }
        else{
            $("#id_destinatario").closest('tr').attr("style", "");
        }        
    });

</script>
{% endblock javascript %}